### ISSUE TITLE
Funkcija Prijava

### ISSUE THREAD

**Issue by blazdob** [dimes123/kosarkaska-ekipa-django#3]
Dodati je potrebno funkcijo prijava, ki naredit to, da je gumb dodaj igralca in gumb izbriši igralca viden le, če je uporabnik prijavljen.

**Comment by blazdob** [comment]
Narejeno, prijava je narejena preko autentifikacije admina, dodana tudi možnost registracije.

**Comment by dimes123** [comment]
Sm popravil izgled, malo je bilo grdo.
