### ISSUE TITLE
Funkcija Najboljši igralec

### ISSUE THREAD

**Issue by blazdob** [dimes123/kosarkaska-ekipa-django#5]
Dodati je potrebno funkcijo najboljši igralec, kjer izbereš igralca, in nasprotno ekipo, ter datum.
izpiše pa podatke najboljših igralcev na tej tekmi.

**Comment by dimes123** [comment]
Glede na to, da pokaže najboljšega igralca, pomojem ni treba izbirati igralca. Še dobro da me imaš Blaž.

**Comment by blazdob** [comment]
Ja to vem, naredu sm samo delujoč Form, ki ga je tko al tko treba spremenit, da potem izbiraš nasprotnika ;) 
je samo demo, Forma.

**Comment by dimes123** [comment]
Narejeno.
